"""Replace stipend with attendee_id

Revision ID: 1eeaab5865cf
Revises: bfb515291b15
Create Date: 2025-05-15 11:30:42.308570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eeaab5865cf'
down_revision = 'bfb515291b15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendee_id', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint(None, ['attendee_id'])
        batch_op.drop_column('stipend')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stipend', sa.BOOLEAN(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('attendee_id')

    # ### end Alembic commands ###
