"""Initial schema with User, Class, Attendee

Revision ID: 3d0a5a54d11f
Revises: 
Create Date: 2025-05-08 10:22:12.181776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d0a5a54d11f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('stipend', sa.Boolean(), nullable=True),
    sa.Column('group', sa.String(length=50), nullable=True),
    sa.Column('comments', sa.String(length=200), nullable=True),
    sa.Column('checked_in', sa.Boolean(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('group_hour', sa.String(length=50), nullable=True),
    sa.Column('group_type', sa.String(length=50), nullable=True),
    sa.Column('time_in', sa.Time(), nullable=True),
    sa.Column('time_out', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendee')
    op.drop_table('class')
    op.drop_table('user')
    # ### end Alembic commands ###
